// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: routing_service.proto
#ifndef GRPC_routing_5fservice_2eproto__INCLUDED
#define GRPC_routing_5fservice_2eproto__INCLUDED

#include "routing_service.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace routing_service {

class RoutingService final {
 public:
  static constexpr char const* service_full_name() {
    return "routing_service.RoutingService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status FindReferenceRoad(::grpc::ClientContext* context, const ::routing_service::TaskPoints& request, ::routing_service::RefRoad* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::routing_service::RefRoad>> AsyncFindReferenceRoad(::grpc::ClientContext* context, const ::routing_service::TaskPoints& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::routing_service::RefRoad>>(AsyncFindReferenceRoadRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::routing_service::RefRoad>> PrepareAsyncFindReferenceRoad(::grpc::ClientContext* context, const ::routing_service::TaskPoints& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::routing_service::RefRoad>>(PrepareAsyncFindReferenceRoadRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void FindReferenceRoad(::grpc::ClientContext* context, const ::routing_service::TaskPoints* request, ::routing_service::RefRoad* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void FindReferenceRoad(::grpc::ClientContext* context, const ::routing_service::TaskPoints* request, ::routing_service::RefRoad* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void FindReferenceRoad(::grpc::ClientContext* context, const ::routing_service::TaskPoints* request, ::routing_service::RefRoad* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::routing_service::RefRoad>* AsyncFindReferenceRoadRaw(::grpc::ClientContext* context, const ::routing_service::TaskPoints& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::routing_service::RefRoad>* PrepareAsyncFindReferenceRoadRaw(::grpc::ClientContext* context, const ::routing_service::TaskPoints& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status FindReferenceRoad(::grpc::ClientContext* context, const ::routing_service::TaskPoints& request, ::routing_service::RefRoad* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::routing_service::RefRoad>> AsyncFindReferenceRoad(::grpc::ClientContext* context, const ::routing_service::TaskPoints& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::routing_service::RefRoad>>(AsyncFindReferenceRoadRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::routing_service::RefRoad>> PrepareAsyncFindReferenceRoad(::grpc::ClientContext* context, const ::routing_service::TaskPoints& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::routing_service::RefRoad>>(PrepareAsyncFindReferenceRoadRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void FindReferenceRoad(::grpc::ClientContext* context, const ::routing_service::TaskPoints* request, ::routing_service::RefRoad* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void FindReferenceRoad(::grpc::ClientContext* context, const ::routing_service::TaskPoints* request, ::routing_service::RefRoad* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void FindReferenceRoad(::grpc::ClientContext* context, const ::routing_service::TaskPoints* request, ::routing_service::RefRoad* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::routing_service::RefRoad>* AsyncFindReferenceRoadRaw(::grpc::ClientContext* context, const ::routing_service::TaskPoints& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::routing_service::RefRoad>* PrepareAsyncFindReferenceRoadRaw(::grpc::ClientContext* context, const ::routing_service::TaskPoints& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_FindReferenceRoad_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status FindReferenceRoad(::grpc::ServerContext* context, const ::routing_service::TaskPoints* request, ::routing_service::RefRoad* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_FindReferenceRoad : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_FindReferenceRoad() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_FindReferenceRoad() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FindReferenceRoad(::grpc::ServerContext* /*context*/, const ::routing_service::TaskPoints* /*request*/, ::routing_service::RefRoad* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFindReferenceRoad(::grpc::ServerContext* context, ::routing_service::TaskPoints* request, ::grpc::ServerAsyncResponseWriter< ::routing_service::RefRoad>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_FindReferenceRoad<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_FindReferenceRoad : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_FindReferenceRoad() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::routing_service::TaskPoints, ::routing_service::RefRoad>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::routing_service::TaskPoints* request, ::routing_service::RefRoad* response) { return this->FindReferenceRoad(context, request, response); }));}
    void SetMessageAllocatorFor_FindReferenceRoad(
        ::grpc::experimental::MessageAllocator< ::routing_service::TaskPoints, ::routing_service::RefRoad>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::routing_service::TaskPoints, ::routing_service::RefRoad>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_FindReferenceRoad() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FindReferenceRoad(::grpc::ServerContext* /*context*/, const ::routing_service::TaskPoints* /*request*/, ::routing_service::RefRoad* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* FindReferenceRoad(
      ::grpc::CallbackServerContext* /*context*/, const ::routing_service::TaskPoints* /*request*/, ::routing_service::RefRoad* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* FindReferenceRoad(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::routing_service::TaskPoints* /*request*/, ::routing_service::RefRoad* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_FindReferenceRoad<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_FindReferenceRoad<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_FindReferenceRoad : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_FindReferenceRoad() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_FindReferenceRoad() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FindReferenceRoad(::grpc::ServerContext* /*context*/, const ::routing_service::TaskPoints* /*request*/, ::routing_service::RefRoad* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_FindReferenceRoad : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_FindReferenceRoad() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_FindReferenceRoad() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FindReferenceRoad(::grpc::ServerContext* /*context*/, const ::routing_service::TaskPoints* /*request*/, ::routing_service::RefRoad* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFindReferenceRoad(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_FindReferenceRoad : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_FindReferenceRoad() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->FindReferenceRoad(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_FindReferenceRoad() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FindReferenceRoad(::grpc::ServerContext* /*context*/, const ::routing_service::TaskPoints* /*request*/, ::routing_service::RefRoad* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* FindReferenceRoad(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* FindReferenceRoad(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_FindReferenceRoad : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_FindReferenceRoad() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::routing_service::TaskPoints, ::routing_service::RefRoad>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::routing_service::TaskPoints, ::routing_service::RefRoad>* streamer) {
                       return this->StreamedFindReferenceRoad(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_FindReferenceRoad() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status FindReferenceRoad(::grpc::ServerContext* /*context*/, const ::routing_service::TaskPoints* /*request*/, ::routing_service::RefRoad* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedFindReferenceRoad(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::routing_service::TaskPoints,::routing_service::RefRoad>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_FindReferenceRoad<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_FindReferenceRoad<Service > StreamedService;
};

}  // namespace routing_service


#endif  // GRPC_routing_5fservice_2eproto__INCLUDED
